### ISSUE TITLE
Code questions

### ISSUE THREAD

**Issue by ghost** [Jhryu30/AnomalyBERT#5]
Hello, thank you for your excellent work.

Are the following two lines missing after line 258 in train.py?

```
x_anomaly[j, tar:tar+leng] = 1
x[j][tar:tar+leng] = _x.transpose(0, 1)
```

Thanks again.

**Comment by coffeetumbler** [comment]
Thank you for your good advice, @wangchz13.

As you said, the code should be inserted after line 258.
Specifically, the indentation of the code on lines 269-270 was incorrect.
We corrected the issue you mentioned immediately.
(But it is okay to execute the previous code on data with categorical columns.)

Thank you.
